/* ---------- data ---------- */
const CARS = [
  { e: "🚗", n: "Červené auto", p: 0, k: "car", c: "#ff4d4d" },
  { e: "🚙", n: "Džíp", p: 150, k: "suv", c: "#2ec27e" },
  { e: "🚕", n: "Taxík", p: 400, k: "car", c: "#ffd23f", x: "taxi" },
  { e: "🚓", n: "Polícia", p: 900, k: "car", c: "#f4f6fa", x: "police" },
  { e: "🚑", n: "Sanitka", p: 1600, k: "van", c: "#f4f6fa", x: "amb" },
  { e: "🚒", n: "Hasiči", p: 2800, k: "van", c: "#e63946", x: "fire" },
  { e: "🛻", n: "Pick-up", p: 4500, k: "pickup", c: "#3a86ff" },
  { e: "🚜", n: "Traktor", p: 7000, k: "tractor", c: "#2ec27e" },
  { e: "🚌", n: "Autobus", p: 11000, k: "bus", c: "#ff8c1a" },
  { e: "🏎️", n: "Formula", p: 18000, k: "formula", c: "#e63946" },
  { e: "🚛", n: "Kamión", p: 28000, k: "truck", c: "#9b5de5" },
  { e: "🚀", n: "Raketa", p: 50000, k: "rocket", c: "#f4f6fa" },
];
const TUNE = {
  col: {
    n: "Farba",
    e: "🎨",
    items: [
      ["def", "Pôvodná", 0],
      ["#ff4d4d", "Červená", 60],
      ["#3a86ff", "Modrá", 60],
      ["#2ec27e", "Zelená", 60],
      ["#ffd23f", "Žltá", 60],
      ["#ff8c1a", "Oranžová", 80],
      ["#9b5de5", "Fialová", 80],
      ["#ff6fb5", "Ružová", 100],
      ["#20c9b8", "Tyrkysová", 120],
      ["#a3e635", "Limetková", 120],
      ["#f4f6fa", "Biela", 100],
      ["#2a2d36", "Čierna", 150],
      ["#8b1e3f", "Bordová", 200],
      ["#7fe3ff", "Ľadová", 300],
      ["#c0c7d2", "Strieborná", 400],
      ["#d4a017", "Zlatá", 800],
      ["rainbow", "Dúhová", 2500],
      ["galaxy", "Galaxia", 3500],
    ],
  },
  pt: {
    n: "Vzor",
    e: "🔳",
    items: [
      ["none", "Bez vzoru", 0],
      ["dots", "Bodky", 250],
      ["checker", "Šachovnica", 400],
      ["zebra", "Zebra", 500],
      ["camo", "Maskáč", 600],
      ["flames", "Plamene", 700],
      ["stars", "Hviezdy", 800],
    ],
  },
  wh: {
    n: "Kolesá",
    e: "🛞",
    items: [
      ["basic", "Obyčajné", 0],
      ["sport", "Športové", 150],
      ["flower", "Kvetinkové", 300],
      ["star", "Hviezdne", 400],
      ["gold", "Zlaté", 700],
      ["big", "Terénne", 900],
      ["fire", "Ohnivé", 1200],
      ["neon", "Neónové", 1500],
    ],
  },
  sp: {
    n: "Krídlo",
    e: "🪽",
    items: [
      ["none", "Žiadne", 0],
      ["small", "Malé krídlo", 200],
      ["big", "Veľké krídlo", 600],
      ["jet", "Raketový motor", 2000],
      ["wings", "Anjelské krídla", 2500],
    ],
  },
  st: {
    n: "Nálepka",
    e: "⭐",
    items: [
      ["none", "Žiadna", 0],
      ["stripes", "Pruhy", 150],
      ["smile", "Smajlík", 150],
      ["bolt", "Blesk", 200],
      ["star", "Hviezda", 200],
      ["heart", "Srdce", 200],
      ["paw", "Labky", 250],
      ["num", "Číslo 7", 300],
      ["rainbow", "Dúha", 300],
      ["flame", "Plamene", 400],
      ["crown", "Korunka", 500],
      ["unicorn", "Jednorožec", 600],
    ],
  },
  rf: {
    n: "Strecha",
    e: "🧳",
    items: [
      ["none", "Nič", 0],
      ["box", "Strešný box", 300],
      ["duck", "Kačička", 350],
      ["siren", "Majáčik", 400],
      ["surf", "Surf", 500],
      ["prop", "Vrtuľka", 600],
    ],
  },
  gl: {
    n: "Neón",
    e: "💡",
    items: [
      ["none", "Bez neónu", 0],
      ["#3a86ff", "Modrý neón", 400],
      ["#ff4fd8", "Ružový neón", 400],
      ["#39ff88", "Zelený neón", 400],
      ["#ffd23f", "Žltý neón", 400],
      ["rainbow", "Dúhový neón", 1500],
    ],
  },
  tr: {
    n: "Stopa",
    e: "💨",
    items: [
      ["none", "Bez stopy", 0],
      ["smoke", "Dym", 200],
      ["sparks", "Iskry", 500],
      ["stars", "Hviezdičky", 700],
      ["hearts", "Srdiečka", 700],
      ["rainbow", "Dúha", 1500],
    ],
  },
  hn: {
    n: "Klaksón",
    e: "📯",
    items: [
      ["classic", "Klasický", 0],
      ["duck", "Kačka", 150],
      ["siren", "Siréna", 300],
      ["trumpet", "Fanfára", 400],
      ["song", "Melódia", 600],
    ],
  },
};
const STK_E = {
  bolt: "⚡",
  star: "⭐",
  heart: "❤️",
  flame: "🔥",
  smile: "😀",
  paw: "🐾",
  rainbow: "🌈",
  crown: "👑",
  unicorn: "🦄",
};
const TUNE_HINT = {
  pt: "Vzor sa nakreslí na karosériu.",
  gl: "Neón svieti pod autom, najkrajší je v noci.",
  tr: "Stopu za autom uvidíš v pretekoch.",
  rf: "Vec na streche vidno všade, aj v meste.",
  hn: "Klaksón zatrúbi na štarte pretekov a v meste, keď ťukneš na auto.",
};
const TRACKS = [
  {
    id: "city",
    n: "Mesto",
    e: "🏙️",
    p: 0,
    len: 38,
    sp: 1,
    m: 1,
    riv: 0,
    road: "#3b4453",
    side: "#7fcf6a",
    side2: "#73c45e",
    edge: "#ffffff",
    lane: "rgba(255,255,255,.8)",
    deco: ["🏢", "🏠", "🌳", "🏬", "🏡", "🌳", "🏫", "🌷"],
    obs: ["🚧", "📦", "🛢️"],
    cross: "🦆",
  },
  {
    id: "forest",
    n: "Les",
    e: "🌲",
    p: 400,
    len: 42,
    sp: 1.05,
    m: 1.3,
    riv: 0.02,
    road: "#454a42",
    side: "#2f8f46",
    side2: "#2a8440",
    edge: "#e9e2c8",
    lane: "rgba(255,255,255,.7)",
    deco: ["🌲", "🌳", "🍄", "🌲", "🪨", "🌲", "🦊", "🌳"],
    obs: ["🪵", "🪨", "🚧"],
    cross: "🦌",
  },
  {
    id: "desert",
    n: "Púšť",
    e: "🌵",
    p: 1200,
    len: 46,
    sp: 1.1,
    m: 1.6,
    riv: 0.035,
    road: "#6b6058",
    side: "#f0cd82",
    side2: "#e8c274",
    edge: "#fff4d6",
    lane: "rgba(255,255,255,.7)",
    deco: ["🌵", "🪨", "🌵", "🏜️", "🌵", "🦂", "🐫", "🌴"],
    obs: ["🌵", "🪨", "🛢️"],
    cross: "🐪",
  },
  {
    id: "snow",
    n: "Sneh",
    e: "❄️",
    p: 3000,
    len: 46,
    sp: 1.05,
    m: 2,
    riv: 0.04,
    slip: true,
    road: "#6f7b8c",
    side: "#f3f7fc",
    side2: "#e4eef8",
    edge: "#bfe4ff",
    lane: "rgba(255,255,255,.85)",
    deco: ["🌲", "⛄", "🌲", "🏔️", "🌲", "🎄", "🦌", "🏠"],
    obs: ["⛄", "🧊", "🪨"],
    cross: "🐧",
  },
  {
    id: "night",
    n: "Noc",
    e: "🌙",
    p: 6000,
    len: 50,
    sp: 1.12,
    m: 2.5,
    riv: 0.05,
    dark: true,
    road: "#2b303b",
    side: "#22432f",
    side2: "#1f3d2b",
    edge: "#ffe9a8",
    lane: "rgba(255,255,255,.7)",
    deco: ["🏠", "🌳", "🏢", "🌳", "🏡", "🌲", "🦉", "🏬"],
    obs: ["🚧", "📦", "🛢️"],
    cross: "🦔",
  },
  {
    id: "space",
    n: "Vesmír",
    e: "🪐",
    p: 15000,
    len: 55,
    sp: 1.2,
    m: 3.2,
    riv: 0.06,
    space: true,
    road: "#2a1f4f",
    side: "#0b0b24",
    side2: "#10102e",
    edge: "#b48cff",
    lane: "rgba(180,140,255,.8)",
    deco: ["🪐", "⭐", "🌍", "✨", "🌙", "☄️", "🛰️", "🌟"],
    obs: ["☄️", "🪨", "🛰️"],
    cross: "👽",
  },
];
const UPS = [
  { id: "bonus", e: "🐷", n: "Zlatá kasička", d: "+15 % mincí vo všetkých hrách", max: 10, p: 120, g: 1.7 },
  { id: "shield", e: "🛡️", n: "Štít", d: "Na štarte pretekov máš štít navyše", max: 4, p: 200, g: 2.3 },
  { id: "turbo", e: "🪙", n: "Mincová cesta", d: "Viac mincí na ceste", max: 8, p: 150, g: 1.8 },
  { id: "tank", e: "⛽", n: "Väčšia nádrž", d: "Benzín vydrží dlhšie", max: 3, p: 300, g: 2.2 },
  { id: "magnet", e: "🧲", n: "Magnet", d: "Pritiahne mince z vedľajších pruhov", max: 1, p: 1500, g: 1 },
  { id: "lupa", e: "🔍", n: "Lupa", d: "Na začiatku pexesa ukáže všetky karty", max: 3, p: 250, g: 2.2 },
  { id: "sponge", e: "🧽", n: "Veľká špongia", d: "Rýchlejšie umývanie áut", max: 3, p: 200, g: 2.2 },
];
const BLDS = [
  { id: "gas", e: "⛽", n: "Benzínka", p: 80, r: 1, u: 1 },
  { id: "wash", e: "🧼", n: "Umyváreň", p: 300, r: 3, u: 2 },
  { id: "shop", e: "🏪", n: "Obchod", p: 900, r: 8, u: 3 },
  { id: "fact", e: "🏭", n: "Továreň", p: 2500, r: 20, u: 5 },
  { id: "hosp", e: "🏥", n: "Nemocnica", p: 6000, r: 45, u: 7 },
  { id: "stad", e: "🏟️", n: "Štadión", p: 14000, r: 100, u: 9 },
  { id: "air", e: "✈️", n: "Letisko", p: 32000, r: 220, u: 11 },
  { id: "ufo", e: "🛸", n: "Vesmírna stanica", p: 75000, r: 500, u: 14 },
];
const GAMES = [
  { id: "race", e: "🏁", n: "Preteky", u: 1, c: "var(--tomato)", cd: "var(--tomatoD)" },
  { id: "pexeso", e: "🃏", n: "Pexeso", u: 1, c: "var(--plum)", cd: "var(--plumD)" },
  { id: "wash", e: "🧽", n: "Umyváreň", u: 1, c: "var(--blue)", cd: "var(--blueD)" },
  { id: "count", e: "🔢", n: "Počítanie", u: 2, c: "var(--sun)", cd: "var(--sunD)", tc: "var(--ink)" },
  { id: "puzzle", e: "🧩", n: "Skladačka", u: 2, c: "var(--grass)", cd: "var(--grassD)" },
  { id: "park", e: "🅿️", n: "Parkovisko", u: 3, c: "var(--orange)", cd: "var(--orangeD)" },
  { id: "color", e: "🖍️", n: "Omaľovánka", u: 2, c: "#ff6fb5", cd: "#d94a92" },
  { id: "repair", e: "🔧", n: "Servis", u: 3, c: "#14a3a3", cd: "#0d7d7d" },
  { id: "maze", e: "🗺️", n: "Bludisko", u: 4, c: "#5b8def", cd: "#3c6ccf" },
  { id: "letters", e: "🔤", n: "Písmenká", u: 5, c: "#e85d75", cd: "#c23f57" },
  { id: "music", e: "🎵", n: "Hudobná garáž", u: 6, c: "#f59f00", cd: "#c77f00" },
  { id: "traffic", e: "🚦", n: "Križovatka", u: 7, c: "#3b4453", cd: "#22283a" },
];
const PAGES = [
  { n: "Vozidlá", e: "🚗", s: ["🚗", "🚕", "🚌", "🚑", "🚜", "🚲", "🚂", "🚁", "🛳️"] },
  { n: "Zvieratá", e: "🐾", s: ["🐶", "🐱", "🐰", "🐘", "🦒", "🐵", "🐧", "🦁", "🦄"] },
  { n: "Jedlo", e: "🍎", s: ["🍎", "🍌", "🍓", "🍉", "🥕", "🍕", "🍦", "🧁", "🎂"] },
  { n: "Vesmír", e: "🚀", s: ["🌍", "🌙", "⭐", "☁️", "🌈", "🪐", "☄️", "👽", "🛸"] },
  { n: "More", e: "🌊", u: 3, s: ["🐠", "🐡", "🐚", "🦀", "🦞", "🐋", "🦈", "🐙", "🧜"] },
  { n: "Dinosaury", e: "🦕", u: 4, s: ["🦴", "🥚", "🌋", "🦎", "🌴", "⛰️", "🌿", "🦕", "🦖"] },
  { n: "Hudba", e: "🎵", u: 6, s: ["🥁", "🎺", "🎻", "🎷", "🎸", "🎹", "🎤", "🎧", "🎼"] },
  { n: "Šport", e: "⚽", u: 7, s: ["⚽", "🏀", "🏈", "⚾", "🎾", "🏓", "🏊", "⛸️", "🏆"] },
  { n: "Rozprávky", e: "🏰", u: 9, s: ["🏰", "👑", "🧙", "🧚", "🐸", "🍄", "🔮", "🧞", "🐉"] },
  { n: "Počasie", e: "⛈️", u: 11, s: ["☀️", "⛅", "🌧️", "⛈️", "❄️", "🌪️", "🌫️", "☂️", "🌬️"] },
  { n: "Hmyz", e: "🐞", u: 13, s: ["🐞", "🐝", "🐜", "🦗", "🕷️", "🐌", "🐛", "🦋", "🦂"] },
  { n: "Jeseň", e: "🍂", season: [9, 10, 11], s: ["🍂", "🍁", "🌰", "🎃", "🦔", "☔", "🥧", "🧣", "🕯️"] },
  { n: "Vianoce", e: "🎄", season: [12, 1], s: ["🎄", "🎅", "🤶", "⛄", "🎁", "🔔", "🦌", "🍪", "🌟"] },
  { n: "Jar", e: "🌸", season: [3, 4, 5], s: ["🌸", "🌷", "🌼", "🌻", "🌱", "🐣", "🐤", "🌦️", "🪁"] },
  { n: "Leto", e: "🏖️", season: [6, 7, 8], s: ["🏖️", "🌊", "🩴", "🕶️", "🍹", "🏄", "⛱️", "🐬", "🍧"] },
];
const ALLS = PAGES.flatMap((p, pi) => p.s.map((s, i) => ({ s, p: pi, gold: i >= p.s.length - 2 })));
function pageOpen(i) {
  const p = PAGES[i];
  if (!p) return false;
  if (p.season) return true;
  return S.lvl >= (p.u || 1);
}
const SEASONS = () => PAGES.filter((p) => p.season);
const weekN = () => Math.floor(dayN() / 7);
const curSeason = () => {
  const A = SEASONS();
  return A[(weekN() + 3) % A.length];
};
const nextSeason = () => {
  const A = SEASONS();
  return A[(weekN() + 4) % A.length];
};
const daysToNext = () => 7 - (dayN() % 7);
function inSeason(p) {
  return p === curSeason();
}
function seasonText(p) {
  return inSeason(p) ? "tento týždeň" : "zriedkavé";
}
const QT = [
  { k: "race", e: "🏁", t: "Zajazdi si preteky", g: [2, 3, 4], game: "race" },
  { k: "win", e: "🥇", t: "Vyhraj preteky na 1. mieste", g: [1, 2], game: "race" },
  { k: "pexeso", e: "🃏", t: "Zahraj pexeso", g: [2, 3], game: "pexeso" },
  { k: "wash", e: "🧽", t: "Umy autá", g: [2, 3], game: "wash" },
  { k: "count", e: "🔢", t: "Zahraj počítanie", g: [1, 2], game: "count" },
  { k: "puzzle", e: "🧩", t: "Poskladaj obrázky", g: [1, 2, 3], game: "puzzle" },
  { k: "park", e: "🅿️", t: "Zaparkuj autá", g: [1, 2], game: "park" },
  { k: "color", e: "🖍️", t: "Vymaľuj obrázok", g: [1, 2], game: "color" },
  { k: "repair", e: "🔧", t: "Oprav autá v servise", g: [1, 2], game: "repair" },
  { k: "maze", e: "🗺️", t: "Prejdi bludisko", g: [1, 2, 3], game: "maze" },
  { k: "letters", e: "🔤", t: "Zahraj písmenká", g: [1, 2], game: "letters" },
  { k: "music", e: "🎵", t: "Zahraj hudobnú garáž", g: [1, 2], game: "music" },
  { k: "traffic", e: "🚦", t: "Riaď križovatku", g: [1, 2], game: "traffic" },
  { k: "raceCoins", e: "🪙", t: "Zober mince na ceste", g: [20, 40, 60], game: "race" },
  { k: "earn", e: "💰", t: "Zarob mince", g: [150, 300, 500], scale: true },
  { k: "collect", e: "🏙️", t: "Vyber mince z mesta", g: [2, 3], city: true },
  { k: "pack", e: "📒", t: "Otvor balíček nálepiek", g: [1, 2] },
  { k: "stars3", e: "⭐", t: "Získaj 3 hviezdy v hre", g: [2, 3] },
];
